<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-VK5R7EG" failures="1" tests="6" name="com.solvd.homework21.GithubTest" time="8.928" errors="0" timestamp="2021-12-25T23:27:43 MSK" skipped="0">
  <testcase classname="com.solvd.homework21.GithubTest" name="verifyRepositoryTest" time="2.197"/>
  <system-out/>
  <testcase classname="com.solvd.homework21.GithubTest" name="verifyUserTest" time="2.174">
    <failure message="name
Expected: РђСЂС‚С‘Рј РџРµС‚СЂРѕРІ
     got: Артём Петров
" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: name
Expected: РђСЂС‚С‘Рј РџРµС‚СЂРѕРІ
     got: Артём Петров

at org.skyscreamer.jsonassert.JSONAssert.assertEquals(JSONAssert.java:482)
at org.skyscreamer.jsonassert.JSONAssert.assertEquals(JSONAssert.java:464)
at com.qaprosoft.carina.core.foundation.api.AbstractApiMethodV2.validateResponse(AbstractApiMethodV2.java:215)
at com.qaprosoft.carina.core.foundation.api.AbstractApiMethodV2.validateResponse(AbstractApiMethodV2.java:243)
at com.solvd.homework21.GithubTest.verifyUserTest(GithubTest.java:54)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- verifyUserTest -->
  <system-out/>
  <testcase classname="com.solvd.homework21.GithubTest" name="checkUpdateRepositoryTest" time="0.642"/>
  <system-out/>
  <testcase classname="com.solvd.homework21.GithubTest" name="checkDeleteRepositoryTest" time="0.611"/>
  <system-out/>
  <testcase classname="com.solvd.homework21.GithubTest" name="checkCreateRepositoryTest" time="2.839"/>
  <system-out/>
  <testcase classname="com.solvd.homework21.GithubTest" name="verifyRepositoryTest" time="0.465"/>
  <system-out/>
</testsuite> <!-- com.solvd.homework21.GithubTest -->
